# Generated by Django 4.0.6 on 2022-07-11 18:57

from django.db import migrations, models
import fitnessWeb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=fitnessWeb.models.get_image_path),
        ),
    ]
