# Generated by Django 4.0.6 on 2022-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0002_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(choices=[('Jake', 'Jake'), ('Bob', 'Bob'), ('Harold', 'Harold'), ('Jenny', 'Jenny'), ('Chris', 'Chris')], max_length=100)),
                ('room', models.IntegerField()),
                ('time', models.TimeField()),
                ('day', models.DateTimeField()),
            ],
        ),
    ]
