# Generated by Django 4.0.6 on 2022-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0003_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='day',
        ),
        migrations.AddField(
            model_name='class',
            name='weekday',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
