# Generated by Django 4.0.6 on 2022-07-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0005_class_description_class_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fitnessWeb.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
