# Generated by Django 4.0.4 on 2022-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0008_message_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('member', 'Member')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
